version: '3.8'

services:
  db_sgcd:
    image: mysql:9.6.0
    container_name: envhub_db_sgcd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - envhub_data:/var/lib/mysql/
      - ./sql_scripts:/docker-entrypoint-initdb.d 

volumes:
  envhub_data: